// Code generated by "stringer -type=Modifier"; DO NOT EDIT.

package aribica

import "strconv"

const _Modifier_name = "PUBLICPRIVATEPROTECTEDVOLATILESYNCHRONIZEDSTATICFINALABSTRACT"

var _Modifier_index = [...]uint8{0, 6, 13, 22, 30, 42, 48, 53, 61}

func (i Modifier) String() string {
	if i < 0 || i >= Modifier(len(_Modifier_index)-1) {
		return "Modifier(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Modifier_name[_Modifier_index[i]:_Modifier_index[i+1]]
}
